Repository LedgerHQ/lib-ledger-core, pull requests merged in 2019-04, with the labels that each got.

#193 Fix Native Segwit
  core/src/bitcoin/BitcoinLikeAddress.cpp
  core/test/integration/transactions/bitcoin_P2WPKH_transaction_tests.cpp
Labels: easy

#187 Patch ERC20LikeAccount::getBalanceHistoryFor.
  core/src/wallet/bitcoin/BitcoinLikeAccount.cpp
  core/src/wallet/common/BalanceHistory.hpp
  core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp
  core/test/CMakeLists.txt
  core/test/common/CMakeLists.txt
  core/test/common/balance_history.cpp
  core/test/common/main.cpp
  core/test/ripple/CMakeLists.txt
Labels: bug

#180 Review password encoding.
  CHANGELOG.md
  core/idl/wallet/wallet_pool.djinni
  core/src/api/WalletPool.hpp
  core/src/jni/jni/WalletPool.cpp
  core/src/wallet/pool/WalletPool.cpp
  core/src/wallet/pool/WalletPool.hpp
  core/src/wallet/pool/api/WalletPoolApi.cpp
  core/src/wallet/pool/api/WalletPoolApi.hpp
  core/src/wallet/pool/api/WalletPoolBuilder.hpp
  core/test/database/BaseFixture.cpp
  core/test/database/pool_tests.cpp
  core/test/integration/BaseFixture.cpp
Labels: easy, enhancement

#194 Fix encryption to pass RecryptClearValues.
  core/src/crypto/AESCipher.cpp
  core/src/preferences/PreferencesBackend.cpp
  core/src/preferences/PreferencesBackend.hpp
  core/test/preferences/preferences_test.cpp
Labels: bug

#197 Fix PreferencesBackend password change (empty new passwords now disable encryption).
  core/test/preferences/preferences_test.cpp
Labels: bug

#195 Implement migration process for bitcoinLikeNetworkParameters
  core/src/wallet/bitcoin/api_impl/BitcoinLikeTransactionApi.cpp
  core/src/wallet/bitcoin/api_impl/BitcoinLikeTransactionApi.h
  core/src/wallet/bitcoin/networks.cpp
  core/src/wallet/bitcoin/networks.hpp
  core/test/integration/CMakeLists.txt
  core/test/integration/synchronization/synchronization_tests.cpp
Labels: enhancement

#208 Fixes/features
  core/idl/wallet/common/wallet.djinni
  core/src/api/RippleLikeMemo.hpp
  core/src/api/Wallet.hpp
  core/src/jni/jni/Wallet.cpp
  core/src/wallet/bitcoin/BitcoinLikeWallet.cpp
  core/src/wallet/bitcoin/BitcoinLikeWallet.hpp
  core/src/wallet/common/AbstractWallet.cpp
  core/src/wallet/common/AbstractWallet.hpp
  core/src/wallet/common/synchronizers/AbstractBlockchainExplorerAccountSynchronizer.h
  core/src/wallet/ethereum/EthereumLikeAccount.cpp
  core/src/wallet/ethereum/EthereumLikeWallet.cpp
  core/src/wallet/ethereum/api_impl/EthereumLikeTransactionApi.cpp
  core/src/wallet/ethereum/api_impl/EthereumLikeTransactionApi.h
  core/src/wallet/ripple/RippleLikeWallet.cpp
  core/test/integration/transactions/ethereum_transaction_tests.cpp
Labels: easy

#213 Fix encryption
  core/src/wallet/pool/WalletPool.cpp
  core/test/integration/BaseFixture.cpp
  core/test/integration/BaseFixture.h
  core/test/integration/account_creation_tests.cpp
Labels: easy

#214 Handle multiple ERC20 transfer events in same ETH transaction
  core/src/wallet/ethereum/ERC20/ERC20LikeAccount.cpp
  core/src/wallet/ethereum/ERC20/ERC20LikeOperation.cpp
  core/src/wallet/ethereum/ERC20/ERC20LikeOperation.h
  core/src/wallet/ethereum/EthereumLikeAccount.cpp
  core/src/wallet/ethereum/explorers/EthereumLikeBlockchainExplorer.h
  core/src/wallet/ethereum/explorers/api/EthereumLikeTransactionParser.cpp
Labels: enhancement

#212 Add getGasPrice and getEstimatedGasLimit on ETH explorers
  core/idl/wallet/ethereum/ethereum_like_wallet.djinni
  core/src/api/BigIntCallback.hpp
  core/src/api/EthereumLikeAccount.hpp
  core/src/jni/jni/BigIntCallback.cpp
  core/src/jni/jni/BigIntCallback.hpp
  core/src/jni/jni/EthereumLikeAccount.cpp
  core/src/wallet/ethereum/EthereumLikeAccount.cpp
  core/src/wallet/ethereum/EthereumLikeAccount.h
  core/src/wallet/ethereum/explorers/EthereumLikeBlockchainExplorer.h
  core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.cpp
  core/src/wallet/ethereum/explorers/LedgerApiEthereumLikeBlockchainExplorer.h
  core/test/integration/CMakeLists.txt
  core/test/integration/ledger_api_blockchain_explorer_tests.cpp
Labels: easy
