Repository LedgerHQ/lib-ledger-core, pull requests merged in 2020-02, with the labels that each got.

#482 Add SSL_SUPPORT configuration to build Core library with SSL support.
  .circleci/build_lib.sh
  CMakeLists.txt
  core/lib/openssl/CMakeLists.txt
  core/src/CMakeLists.txt
  core/src/database/PostgreSQLBackend.cpp
  core/src/database/PostgreSQLBackend.h
Labels: dependencies

#483 Make fixes and changes to prepare the new WD release
  core/src/database/migrations.hpp
  core/src/wallet/common/synchronizers/AbstractBlockchainExplorerAccountSynchronizer.h
  core/src/wallet/ethereum/explorers/api/EthereumLikeTransactionParser.cpp
Labels: bug, enhancement

#498 Add support for failover behavior in soci connection pools.
  core/idl/database/database.djinni
  core/lib/soci/core/session.cpp
  core/lib/soci/core/session.h
  core/lib/soci/core/soci-backend.h
  core/lib/soci_postgresql/session.cpp
  core/lib/soci_postgresql/soci-postgresql.h
  core/lib/soci_sqlite3/session.cpp
  core/lib/soci_sqlite3/soci-sqlite3.h
  core/src/api/DatabaseConnection.hpp
  core/src/database/proxy_backend/session.cpp
  core/src/database/proxy_backend/soci-proxy.h
  core/src/jni/jni/DatabaseConnection.cpp
  core/src/jni/jni/DatabaseConnection.hpp
  core/test/database/MemoryDatabaseProxy.cpp
  core/test/database/MemoryDatabaseProxy.h
Labels: bug

#501 Fix OpenSSL’s BLAKE2b heap memory corruption.
  core/lib/CMakeLists.txt
  core/lib/blake/CMakeLists.txt
  core/lib/blake/blake2b.cpp
  core/lib/blake/blake2b.h
  core/src/CMakeLists.txt
  core/src/crypto/BLAKE.cpp
  core/src/tezos/TezosLikeAddress.cpp
Labels: bug

#451 DGB: support of bech32 addresses
  core/src/bitcoin/bech32/Bech32Factory.cpp
  core/src/bitcoin/bech32/Bech32Parameters.cpp
  core/test/bitcoin/address_test.cpp
  core/test/integration/BaseFixture.cpp
  core/test/integration/BaseFixture.h
  core/test/integration/synchronization/synchronization_tests.cpp
Labels: enhancement

#458 LTC: support of bech32 addresses
  core/src/bitcoin/bech32/Bech32Factory.cpp
  core/src/bitcoin/bech32/Bech32Parameters.cpp
  core/test/bitcoin/address_test.cpp
  core/test/integration/BaseFixture.cpp
  core/test/integration/BaseFixture.h
  core/test/integration/CMakeLists.txt
  core/test/integration/synchronization/synchronization_tests.cpp
Labels: enhancement

#492 Sync token removal in reorganisation use case
  core/idl/wallet/configuration.djinni
  core/src/api/Configuration.cpp
  core/src/api/Configuration.hpp
  core/src/wallet/common/synchronizers/AbstractBlockchainExplorerAccountSynchronizer.h
Labels: bug
